/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCategorizeRouteImport } from './routes/_authed/categorize'
import { Route as AuthedConnectRouteImport } from './routes/_authed/connect'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed/transactions'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEnablebankingCallbackRouteImport } from './routes/api/enablebanking/callback'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategorizeRoute = AuthedCategorizeRouteImport.update({
  id: '/categorize',
  path: '/categorize',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConnectRoute = AuthedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnablebankingCallbackRoute =
  ApiEnablebankingCallbackRouteImport.update({
    id: '/api/enablebanking/callback',
    path: '/api/enablebanking/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/categorize': typeof AuthedCategorizeRoute
  '/connect': typeof AuthedConnectRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/enablebanking/callback': typeof ApiEnablebankingCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/categorize': typeof AuthedCategorizeRoute
  '/connect': typeof AuthedConnectRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/enablebanking/callback': typeof ApiEnablebankingCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/categorize': typeof AuthedCategorizeRoute
  '/_authed/connect': typeof AuthedConnectRoute
  '/_authed/transactions': typeof AuthedTransactionsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/enablebanking/callback': typeof ApiEnablebankingCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categorize'
    | '/connect'
    | '/transactions'
    | '/api/auth/$'
    | '/api/enablebanking/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/categorize'
    | '/connect'
    | '/transactions'
    | '/'
    | '/api/auth/$'
    | '/api/enablebanking/callback'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/categorize'
    | '/_authed/connect'
    | '/_authed/transactions'
    | '/_authed/'
    | '/api/auth/$'
    | '/api/enablebanking/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEnablebankingCallbackRoute: typeof ApiEnablebankingCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categorize': {
      id: '/_authed/categorize'
      path: '/categorize'
      fullPath: '/categorize'
      preLoaderRoute: typeof AuthedCategorizeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/connect': {
      id: '/_authed/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthedConnectRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enablebanking/callback': {
      id: '/api/enablebanking/callback'
      path: '/api/enablebanking/callback'
      fullPath: '/api/enablebanking/callback'
      preLoaderRoute: typeof ApiEnablebankingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedCategorizeRoute: typeof AuthedCategorizeRoute
  AuthedConnectRoute: typeof AuthedConnectRoute
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCategorizeRoute: AuthedCategorizeRoute,
  AuthedConnectRoute: AuthedConnectRoute,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEnablebankingCallbackRoute: ApiEnablebankingCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
